# Configure here general information about the environment, such as the server connection details for example
# No information about specific project should appear here

#----- SonarQube server URL (default to SonarCloud)
sonar.host.url=http://localhost:9000
sonar.projectKey=CPT_S-581-taigo
sonar.projectName=CPT_S-581-taigo
sonar.sources=src
sonar.token=sqp_8f557bb1d7e849b080a37a76ab55f62d3703de74
#sonar.scanner.proxyHost=myproxy.mycompany.com
#sonar.scanner.proxyPort=8002
